apiVersion: apps/v1
kind: Deployment
metadata:
  name: node1
  labels:
    app: 7node
    node: node1
spec:
  nodeSelector:
    node: node1
  replicas: 1
  selector:
    matchLabels:
      app: 7node
  template:
    metadata:
      labels:
        app: 7node
        node: node1
    spec:
      containers:
      - name: 7node
        image: markpengisme/k8s:quorum
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo hello; sleep 10;done"]
        ports:
        - name: raftport
          containerPort: 50400
        - name: rpcport
          containerPort: 22000
        - name: ipc
          containerPort: 21000
        - name: geth
          containerPort: 9000
        volumeMounts:
        - mountPath: /home/7nodes
          name: git-volume

      volumes:
      - name: git-volume
        gitRepo:
          repository: "https://github.com/markpengisme/Cluster_File.git"


