kind: Service
apiVersion: v1
metadata:
  labels:
    node: node2
  name: nodesvc2
spec:
  selector:
    node: node2
  ports:
  - name: ipc
    port: 21000
    targetPort: 21000
  - name: raftport
    port: 50400
    targetPort: 50400
  - name: rpcport
    port: 22000
    targetPort: 22000
  - name: geth
    port: 9000
    targetPort: 9000
  type: LoadBalancer
